apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: org2-net-ca
  namespace: org2-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: org2-net-ca
  chart:
    git: ssh://git@github.com/sivaramsk/blockchain-automation-framework.git
    ref: kind
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: org2-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: org2-admin
    storage:
      storageclassname: org2sc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://192.168.0.104:8200
      authpath: org2-net-auth
      secretcert: secret/crypto/peerOrganizations/org2-net/ca?ca.org2-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/org2-net/ca?org2-net-CA.key
      secretadminpass: secret/credentials/org2-net/ca/org2?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
