# Default values for indy-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: supplychain-bes
  namespace:

  #Provide the name for indy-key-mgmt release
  #Eg. name: indy-key-mgmt
  name:

image:
  #Provide the image repository for the indy-key-mgmt container
  #Eg. repository: indy-key-mgmt:latest
  repository:

  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret:


vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address:

  #Provide the key path for vault
  #Eg. authpath: provider.stewards
  authpath:

  #Provide the identity for vault
  #Eg. role: my-identity
  role:

  serviceaccountname: 

  orionprefix: 
