#
---
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    LifecycleEndorsement:
        Type: ImplicitMeta
        Rule: "ANY Endorsement"
    Endorsement:
        Type: ImplicitMeta
        Rule: "ANY Endorsement"
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Organizations:

#
  - &ordorgOrg
    Name: ordorgMSP
    ID: ordorgMSP
    MSPDir: ./crypto-config/ordererOrganizations/ordorg-net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordorgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordorgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordorgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ordorgMSP.member')"
    
#
  - &org1Org
    Name: org1MSP
    ID: org1MSP
    MSPDir: ./crypto-config/peerOrganizations/org1-net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('org1MSP.member')"
          
    AnchorPeers:
      # AnchorPeers defines the location of peers which can be used
      # for cross org gossip communication.  Note, this value is only
      # encoded in the genesis block in the Application section context
      - Host: peer0.org1-net
        Port: 7051
#
  - &org2Org
    Name: org2MSP
    ID: org2MSP
    MSPDir: ./crypto-config/peerOrganizations/org2-net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('org2MSP.member')"
          
    AnchorPeers:
      # AnchorPeers defines the location of peers which can be used
      # for cross org gossip communication.  Note, this value is only
      # encoded in the genesis block in the Application section context
      - Host: peer0.org2-net
        Port: 7051
#
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer1.ordorg-net:7050

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 1024 KB
  EtcdRaft:
    Consenters:
      - Host: orderer1.staging.kluster.emulya.com
        Port: 8443
        ClientTLSCert: ./crypto-config/ordererOrganizations/ordorg-net/orderers/orderer1.ordorg-net/tls/server.crt
        ServerTLSCert: ./crypto-config/ordererOrganizations/ordorg-net/orderers/orderer1.ordorg-net/tls/server.crt
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
#
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
        - Host: orderer1.staging.kluster.emulya.com
          Port: 8443
          ClientTLSCert: ./crypto-config/ordererOrganizations/ordorg-net/orderers/orderer1.ordorg-net/tls/server.crt
          ServerTLSCert: ./crypto-config/ordererOrganizations/ordorg-net/orderers/orderer1.ordorg-net/tls/server.crt
      Organizations:
        - *ordorgOrg
    Consortiums:
      MyConsortium:
        Organizations:
          - *org1Org
          - *org2Org
  AllChannel:
    <<: *ChannelDefaults
    Consortium: MyConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *org1Org
        - *org2Org
#
