kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: org1sc
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
