apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: org1-net-ca
  namespace: org1-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: org1-net-ca
  chart:
    git: ssh://git@github.com/sivaramsk/blockchain-automation-framework.git
    ref: try2
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: org1-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.5
    server:
      name: ca
      tlsstatus: true
      admin: org1-admin
    storage:
      storageclassname: org1sc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://vault-test.eastus.azurecontainer.io:8200
      authpath: org1-net-auth
      secretcert: secret/crypto/peerOrganizations/org1-net/ca?ca.org1-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/org1-net/ca?org1-net-CA.key
      secretadminpass: secret/credentials/org1-net/ca/org1?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
