apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-org1
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-org1
  chart:
    git: ssh://git@github.com/sivaramsk/blockchain-automation-framework.git
    ref: dotest
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: org1-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://159.65.153.150:8200
      authpath: org1-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org1-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/org1-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.ordorg-net:7050
    anchorstx: |-
      CtMCChgKFggCGgYIxLzh/gUiCmFsbGNoYW5uZWwStgIKswIKCmFsbGNoYW5uZWwSYBJeCgtBcHBs
      aWNhdGlvbhJPCAESSwoHb3JnMU1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJz
      EgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABrCARK/AQoLQXBwbGljYXRpb24SrwEIARKq
      AQoHb3JnMU1TUBKeAQgBGgcKA01TUBIAGlIKC0FuY2hvclBlZXJzEkMSOQo3CjJwZWVyMC5vcmcx
      LW5ldC5vcmcxLW5ldC5zdGFnaW5nLmtsdXN0ZXIuZW11bHlhLmNvbRD7QRoGQWRtaW5zIgsKB1Jl
      YWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACoGQWRtaW5z

