apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: invoke-org3-allchannel-fabcar1
  namespace: org3-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: invoke-org3-allchannel-fabcar1
  chart:
    git: ssh://git@github.com/sivaramsk/blockchain-automation-framework.git
    ref: kind
    path: platforms/hyperledger-fabric/charts/invoke_chaincode
  values:
    metadata:
      namespace: org3-net
      network:
        version: 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.org3-net:7051
      localmspid: org3MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://do-vault.eastus.azurecontainer.io:8200
      authpath: org3-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org3-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/org3-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordorg-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: fabcar
      version: 1
      instantiationarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
