apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ordorg-orderer1
  namespace: ordorg-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ordorg-orderer1
  chart:
    git: ssh://git@github.com/sivaramsk/blockchain-automation-framework.git
    ref: dotest
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: ordorg-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer1
      loglevel: info
      localmspid: ordorgMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: ordorgsc
      storagesize: 1Gi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://159.65.153.150:8200
      role: vault-role
      authpath: ordorg-net-auth
      secretprefix: secret/crypto/ordererOrganizations/ordorg-net/orderers/orderer1.ordorg-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: orgorg-net.staging.kluster.emulya.com

    genesis: |-
      
