---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-crypto-pvc
  namespace: {{ $.Values.metadata.namespace }}
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-pvc
  namespace: {{ $.Values.metadata.namespace }}
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}

