---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-crypto-pvc
  namespace: {{ $.Values.metadata.namespace }}
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-pvc
  namespace: {{ $.Values.metadata.namespace }}
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

